name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build com Maven
        run: mvn clean install
        working-directory: ./devcalc-api

      - name: Executar Testes
        run: mvn test
        working-directory: ./devcalc-api

  package:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Empacotar aplicação
        run: mvn package
        working-directory: ./devcalc-api

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Mensagem de simulação de deploy
        run: echo "Deploy realizado com SUCESSO!"

  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar dependências do Checkstyle
        run: mvn install -DskipTests
        working-directory: ./devcalc-api

      - name: Executar Checkstyle
        run: mvn checkstyle:checkstyle
        working-directory: ./devcalc-api
