name: CI Pipeline Manual

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Executar testes automatizados?"
        required: true
        default: true
        type: boolean
      run_lint:
        description: "Executar verificação de estilo (Checkstyle)?"
        required: true
        default: true
        type: boolean

jobs:
  lint:
    if: ${{ github.event.inputs.run_lint == 'true' }}
    name: Verificar estilo de código (Checkstyle)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: mvn install -DskipTests
      - run: mvn checkstyle:checkstyle

  test:
    if: ${{ github.event.inputs.run_tests == 'true' }}
    name: Executar Testes Automatizados
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: mvn tset

  package:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - run: echo "Deploy realizado com SUCESSO!"
