name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml

  package:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Empacotar aplicação
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Mensagem de simulação de deploy
        run: echo "Deploy realizado com SUCESSO!"
