name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Executar testes automatizados?"
        required: true
        default: true
        type: boolean
      run_lint:
        description: "Executar verificação de estilo (Checkstyle)?"
        required: true
        default: true
        type: boolean

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    if: ${{ github.event.inputs.run_lint == 'true' }}
    name: Verificar estilo de código (Checkstyle)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar dependências (sem testes)
        run: mvn install -DskipTests

      - name: Executar Checkstyle
        run: mvn checkstyle:checkstyle

  test:
    if: ${{ github.event.inputs.run_tests == 'true' }}
    name: Executar Testes Automatizados
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Executar testes
        run: mvn test

  package:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Empacotar aplicação
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Mensagem de simulação de deploy
        run: echo "Deploy realizado com SUCESSO!"
