name: Pipeline de Deploy Automatizado

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy-ambiente-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    environment:
      name: dev
    defaults:
      run:
        shell: powershell

    steps:
      - name: Informações de execução
        run: |
          Write-Output "[INFO] Executado por: ${{ github.actor }}"
          Write-Output "[INFO] Sistema operacional: ${{ runner.os }}"

      - name: Deploy para ambiente DEV
        run: |
          Write-Output "[DEPLOY] Iniciando publicação em ambiente de desenvolvimento"
          Write-Output "[DEPLOY] ENV_TYPE (dev): ${{ vars.ENV_TYPE }}"
          Write-Output "[SUCCESS] Deploy DEV concluído com sucesso"

  deploy-ambiente-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment:
      name: prod
    defaults:
      run:
        shell: powershell

    steps:
      - name: Informações de execução
        run: |
          Write-Output "[INFO] Executado por: ${{ github.actor }}"
          Write-Output "[INFO] Sistema operacional: ${{ runner.os }}"

      - name: Deploy para ambiente PROD
        run: |
          Write-Output "[DEPLOY] Iniciando publicação no ambiente de produção"
          Write-Output "[SECURE] Token de acesso: ${{ secrets.PROD_KEY }}"
          Write-Output "[PENDING] Aguardando aprovação para finalizar deploy PROD"
