name: Teste Runner Local

on:
  workflow_dispatch:

jobs:
  run-local:
    runs-on: self-hosted
    steps:
      - name: Exibir sistema operacional
        run: systeminfo

      - name: Exibir versão do Java
        run: java -version

      - name: Testar comando PowerShell simples
        run: Get-Date
