name: Teste com Variáveis e Secrets

on:
  workflow_dispatch:

jobs:
  exibir-configuracoes:
    runs-on: self-hosted

    steps:
      - name: Exibindo ambiente da aplicação
        run: echo "Ambiente atual: ${{ vars.APP_MODE }}"

      - name: Contato de suporte
        run: echo "Entre em contato: ${{ vars.SUPPORT_EMAIL }}"

      - name: Operação segura com token
        env:
          TOKEN: ${{ secrets.PROD_TOKEN }}
        run: |
          echo "Iniciando tarefa protegida..."
          echo "Token carregado com sucesso para uso interno"
