name: Uso de Segredos e Variáveis

on:
  workflow_dispatch:

jobs:
  variaveis-e-secrets:
    runs-on: self-hosted

    steps:
      - name: Exibir APP_MODE
        run: 'echo Modo Aplicação: ${{ vars.APP_MODE }}'

      - name: Exibir SUPPORT_EMAIL
        run: 'echo Suporte Email: ${{ vars.SUPPORT_EMAIL }}'

      - name: Simular tarefa sensível usando secret
        run: |
          echo Executando task protegida por token...
          echo Token carregado com sucesso!
        env:
          TOKEN: ${{ secrets.PROD_TOKEN }}
