name: Uso de Variáveis e Segredos

on:
  workflow_dispatch:

jobs:
  exibir-configuracoes:
    runs-on: self-hosted

    steps:
      - name: Exibir modo da aplicação
        run: echo "APP_MODE: ${{ vars.APP_MODE }}"

      - name: Exibir e-mail de suporte
        run: echo "SUPPORT_EMAIL: ${{ vars.SUPPORT_EMAIL }}"

      - name: Simular uso de segredo (token)
        run: |
          echo "Executando ação sensível..."
          echo "Token: $TOKEN"
        env:
          TOKEN: ${{ secrets.PROD_TOKEN }}
